### PR TITLE
Include exception thrower lines in coverage matrix.

### LINKED ISSUE #33: Include lines that throw exceptions in coverage
Flacoco does not well treat the cases when the cases throws an exception.

### PR DESCRIPTION
**Pull request by andre15silva**
Closes #33 

Lines that throw exceptions are identified by parsing the stack trace of each failure.

The heuristic behind the parser is the following:
- Starts from the top of the stack trace
- Ignores native calls
- Ignores classes that are not present in the coverage computed by JaCoCo (for instance, `org.junit.Assert` shows up first in the stack traces of tests that fail due to failed assertions from that library)
- All other lines are registered, since they are:
	- From the project we are analyzing
	- Being executed when the exception was thrown, and because of that not registered by JaCoCo.

Tested on `math70` too, where it did find 3 more lines being covered where they weren't counted before.

### CODE REVIEW

**Comment by andre15silva** [comment]
Right now, in Windows, the stack trace recorded contains only the exception thrown:

Windows:
```
java.lang.NullPointerException
```

Linux/MacOS:
```
java.lang.NullPointerException
	at fr.spoonlabs.FLtest1.Calculator.calculate(Calculator.java:22)
	at fr.spoonlabs.FLtest1.CalculatorTest.testMod(CalculatorTest.java:42)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at eu.stamp_project.testrunner.runner.JUnit4Runner.run(JUnit4Runner.java:63)
	at eu.stamp_project.testrunner.runner.coverage.JUnit4JacocoRunnerCoveredResultPerTestMethod.executeCoveredTestPerTestMethod(JUnit4JacocoRunnerCoveredResultPerTestMethod.java:32)
	at eu.stamp_project.testrunner.runner.coverage.JacocoRunnerCoveredResultPerTestMethod.runCoveredTestResultPerTestMethod(JacocoRunnerCoveredResultPerTestMethod.java:64)
	at eu.stamp_project.testrunner.runner.coverage.JUnit4JacocoRunnerCoveredResultPerTestMethod.main(JUnit4JacocoRunnerCoveredResultPerTestMethod.java:49)
```

**Comment by andre15silva** [comment]
https://github.com/alexscheitlin/java-stack-trace-parser/pull/1 fixes the bug.

Module names weren't being parsed.

I suggest we wait to see if the project maintainer is still active, and if he isn't then we can just copy it here since it is under the MIT License.

**Comment by andre15silva** [comment]
Added https://github.com/alexscheitlin/java-stack-trace-parser/ to test and potentially merge it with flacoco.

**Comment by andre15silva** [comment]
@martinezmatias I propose we merge as it is, so we don't have to wait for the other project.

If/When we get the changes merged, we can always revert the merge here and use it as a dependency.

**Comment by martinezmatias** [comment]
Hi @andre15silva 

> Starts from the top of the stack trace
> Ignores native calls
> Ignores classes that are not present in the coverage computed by JaCoCo (for instance, org.junit.Assert shows up first in > the stack traces of tests that fail due to failed assertions from that library)
> All other lines are registered, since they are:
> From the project we are analyzing
>Being executed when the exception was thrown, and because of that not registered by JaCoCo

It seems great for me.


> If/When we get the changes merged, we can always revert the merge here and use it as a dependency.

It's a good strategy. Once he merged and publish the new version at https://jitpack.io/#alexscheitlin/java-stack-trace-parser, we can remove the files and and the dependencies.


Merged!

**Pull request merged**
