### PR TITLE
feat: include executed statements of exception throwing block ignored by Jacoco

### PR DESCRIPTION
**Pull request by andre15silva**
Minimizes https://github.com/SpoonLabs/flacoco/issues/109

When the source code is available, we now include the statements of the block where an exception was thrown. 

This way, the executed statements just before the exception, which might be ignored by Jacoco due to the exception limitation, are included in the coverage result.

This is not a complete fix since, sometimes, the stack-trace is lost in try/catch's of the original project.

### CODE REVIEW

**Comment by andre15silva** [comment]
We are missing a test case and some documentation. Opening for CI.

Already works locally with Nopol's (`cl2`, `cl4`, and `cm1`)

**Comment by monperrus** [comment]
really cool.

**Comment by andre15silva** [comment]
It is ready for review.

Pointer to the changes: https://github.com/SpoonLabs/flacoco/pull/118/files#diff-b2d5c3e7b321712fedb49b653a7da0291773aa97e0a772c0085c659b5eaf12c9

All of the files before belong to the bug `cl2`.

**Comment by monperrus** [comment]
thanks a lot @andre15silva

**Pull request merged**
