### PR TITLE
Automatic test framework detection

### LINKED ISSUE #34: Automated selection of test runner
Flacoco should be able to automatically select, given a project P given as input, the test runner according to the test framework used by P

### PR DESCRIPTION
**Pull request by andre15silva**
Includes separation of the coverage runner logic into different strategies according to the test frameworks.

Includes new logic in test detection.

Includes new tests for JUnit3 and a mixed project with tests from JUnit3, JUnit4 and JUnit5.

Closes #34.
Related to #31.

### CODE REVIEW

**Comment by andre15silva** [comment]
Ready as soon as https://github.com/STAMP-project/test-runner/pull/99 is merged.

**Comment by andre15silva** [comment]
Follow-up to the discussion in #34, I ended up using the heuristics that are already implemented in `test-runner`.

Then, I run all the tests, even if there is a mix of test frameworks being used.

**Comment by martinezmatias** [comment]
Hi André

That's a great feature.
So, If I well understand, now we have one test strategy associated to each test [(here)](https://github.com/SpoonLabs/flacoco/pull/45/files#diff-9c0726e7e614e21bbcd0bd10dc38585eab534950b0bbd1142019482d46467132R50) instead of being associated to the test suite (all the test). Then, for each test, the corresponding strategy is executed [(here)](https://github.com/SpoonLabs/flacoco/pull/45/files#diff-e8e9d2537b6437450d3a4de84775db1a603f074612a89b661ff7271ae26fbf50R34). 

This strategy is fine for me.  However, in the future, we may rethink the strategy for targeting the scalability issue: Ideally, it would be nice if we call to each strategy once, passing a list of test cases that correspond to that strategy. Unfortunately, TestRunner is not capable of returning us the coverage per test. (That's why we currently have to call `test runner ` once per each test.



Regards
Matias

**Comment by andre15silva** [comment]
> Hi André

Hi Matias

> So, If I well understand, now we have one test strategy associated to each test [(here)](https://github.com/SpoonLabs/flacoco/pull/45/files#diff-9c0726e7e614e21bbcd0bd10dc38585eab534950b0bbd1142019482d46467132R50) instead of being associated to the test suite (all the test). Then, for each test, the corresponding strategy is executed [(here)](https://github.com/SpoonLabs/flacoco/pull/45/files#diff-e8e9d2537b6437450d3a4de84775db1a603f074612a89b661ff7271ae26fbf50R34).

Small correction: we have one test strategy associated to each `TestInformation`, which points to a test class and one or more methods. Then, we execute iterate over the list of those objects, and execute all the methods inside each of them at the same time.

> This strategy is fine for me. However, in the future, we may rethink the strategy for targeting the scalability issue: Ideally, it would be nice if we call to each strategy once, passing a list of test cases that correspond to that strategy. Unfortunately, TestRunner is not capable of returning us the coverage per test. (That's why we currently have to call `test runner ` once per each test.

For sure. `test-runner` actually already supports this, and it would be quite easy to do the change **but** there is a problem with same named methods form different classes (see https://github.com/STAMP-project/test-runner/issues/86#issuecomment-867439084). Once that is fixed, the change to running everything at once is easy enough, as we only need to change `TestInformation` and adapt the `test-runner` calls inside of each strategy.

**Comment by martinezmatias** [comment]
> Small correction: we have one test strategy associated to each TestInformation, which points to a test class and one or more methods. Then, we execute iterate over the list of those objects, and execute all the methods inside each of them at the same time

Thanks for the clarification :)

**Comment by andre15silva** [comment]
Ready for review as STAMP-project/test-runner#99 has been merged.

**Comment by andre15silva** [comment]
Ok, this one can be merged now.

**Pull request merged**
