### PR TITLE
Flacoco default API

### PR DESCRIPTION
**Pull request by andre15silva**
## Changelog
- Refactor Flacoco's structure
- Refactor test suite
- Implement Default API

### CODE REVIEW

**Comment by andre15silva** [comment]
@martinezmatias I implemented a draft of the Flacoco API for Spoon.

As suggested, the keys are `CtStatement`s.

The Spoon related processing occurs in the classes under https://github.com/andre15silva/flacoco/tree/api-alpha/src/main/java/fr/spoonlabs/flacoco/utils/spoon.

https://github.com/andre15silva/flacoco/blob/api-alpha/src/main/java/fr/spoonlabs/flacoco/utils/spoon/SpoonLocalizedFaultFinder.java is the processor I use to retrieve `CtStatement`s from the entire model given a qualified class name and the line number.

Now, two issues arise:

 - The lines returned by Jacoco do not always match a `CtStatement` that is contained only inside that line. To circumvent this, I accept all `CtStatement`s whose position contains the line in question [1], and then pick the best-fit. It works well so far, the only issue is that this won't perfectly match the default mode (e.g. [2], where `fr/spoonlabs/FLtest1/Calculator@-@6` gets converted into a CtStatement that starts in line 5. This is the discussed empty constructor/method issue, where the conversion returns an empty block). I'm not entirely convinced this is an actual issue.

- As in [2], two different lines, in this case `fr/spoonlabs/FLtest1/Calculator@-@5` and `fr/spoonlabs/FLtest1/Calculator@-@6` get matched to the same `CtStatement`. This results in the output being of a different size compared to the default mode, and in the need of a "suspiciousness score merge technique". I think most cases will have the same suspiciousness score when this happens tho. My suggestion is that we merge them and use the highest score. WDYT?

[1] https://github.com/andre15silva/flacoco/blob/48955497a30126157d78ffebd18c1312b288f9ae/src/main/java/fr/spoonlabs/flacoco/utils/spoon/SpoonLocalizedFaultFinder.java#L36-L80

[2] 
<details> 
<summary>Example issues</summary>

```
fr/spoonlabs/FLtest1/Calculator@-@5
{
}
(/home/andre/Repos/flacoco/examples/exampleFL1/FLtest1/src/main/java/fr/spoonlabs/FLtest1/Calculator.java:5)

fr/spoonlabs/FLtest1/Calculator@-@6
{
}
(/home/andre/Repos/flacoco/examples/exampleFL1/FLtest1/src/main/java/fr/spoonlabs/FLtest1/Calculator.java:5)
</details>

**Comment by martinezmatias** [comment]
Hi @Andre

> To circumvent this, I accept all CtStatements whose position contains the line in question [1], and then pick the best-fit.

How do you determine the best fit? 

FYI: For Astor I have created a simple strategy, please check the package [here](https://github.com/SpoonLabs/astor/tree/bcc8463eeb00545f921f9216be694807014263ea/src/main/java/fr/inria/astor/core/faultlocalization/bridgeFLSpoon). (I thought I had pointed you the code previously, sorry if I forgot)

> I accept all CtStatements whose position contains the line in question [1]
In fact, In astor I return all elements that have the line number indicated by the Fault localization, without filtering.
E.g., if the have suspicious line X, then we consider all ctelements (or CTExpressions) that are written in X.


Do you want we discuss this feature in a separate issue? (As this PR has many features)

**Comment by andre15silva** [comment]
> Hi @andre

Hi @martinezmatias
 
> > To circumvent this, I accept all CtStatements whose position contains the line in question [1], and then pick the best-fit.
> 
> How do you determine the best fit?

First, I match all `CtStatement`s whose position (`<startLine, endLine>`) contains the given line. Then:

> 	 * Given a list of CtStatement, returns the best fit, i.e.:
	 * - If possible, the top-most CtStatement whose position is just the given lineNumber
	 * - If not, the CtStatement whose position includes the given lineNumber and amplitude is smallest

> FYI: For Astor I have created a simple strategy, please check the package [here](https://github.com/SpoonLabs/astor/tree/bcc8463eeb00545f921f9216be694807014263ea/src/main/java/fr/inria/astor/core/faultlocalization/bridgeFLSpoon). (I thought I had pointed you the code previously, sorry if I forgot)
> 
> > I accept all CtStatements whose position contains the line in question [1]
> > In fact, In astor I return all elements that have the line number indicated by the Fault localization, without filtering.
> > E.g., if the have suspicious line X, then we consider all ctelements (or CTExpressions) that are written in X.

Yes, I based mine of off that, but it has two issues:

- First, it returns more than one `CtStatement`. This is ok, but returning the top-most `CtStatement` results in the same information and is simpler for the API.
- Second, there are some cases where there is no `CtStatement` whose `startLine == endLine == faultyLine`. This is the case I pointed above.

 > Do you want we discuss this feature in a separate issue? (As this PR has many features)

We can go that. I'll separate the Spoon API from this PR and finish the test cases.

**Comment by martinezmatias** [comment]
Hi @andre15silva 

> First, it returns more than one CtStatement. This is ok, but returning the top-most CtStatement results in the same information and is simpler for the API.

Okay, it's a good strategy to simplify the output.

Regards
Matias

**Comment by andre15silva** [comment]
Ready for review @martinezmatias

**Comment by martinezmatias** [comment]
> Ready for review @martinezmatias

It seems fine for me.

Thanks @andre15silva , merged.

**Pull request merged**
