### PR TITLE
Add warning message for SBFL when memory is below 4GiB threshold

### PR DESCRIPTION
**Pull request by andre15silva**
Related with #121

### CODE REVIEW

**Comment by monperrus** [comment]
Thanks @andre15silva  CI failing?

**Comment by andre15silva** [comment]
> Thanks @andre15silva CI failing?

Unrelated to the PR

> Error:  Failed to execute goal on project flacoco: Could not resolve dependencies for project com.github.spoonlabs:flacoco:jar:1.0.3-SNAPSHOT: Could not find artifact eu.stamp-project:test-runner:jar:3.1.4-SNAPSHOT -> [Help 1]

I've restarted the CI

**Comment by andre15silva** [comment]
> Unrelated to the PR, the snapshot repository probably wasn't synced everywhere

This aged poorly. It was actually related to the PR (snapshot repository was missing, and locally I had installed `test-runner`)

I was induced in error because we had some green jobs and I had forgotten that some jobs are instant greens due to CI configuration intricacies.

**Comment by monperrus** [comment]
great, thanks!

**Pull request merged**
