### PR TITLE
Command line interface using picocli

### PR DESCRIPTION
**Pull request by martinezmatias**
Related to issue #39

### CODE REVIEW

**Comment by andre15silva** [comment]
We should merge #35 first, as it includes some new configurable options.

Also, did you use JUnit5 annotations on purpose for the `FlacocoMainTest`?

**Comment by martinezmatias** [comment]
> We should merge #35 first, as it includes some new configurable options.

I did not include all configurations, we will add then later as we introduce new features.


> Also, did you use JUnit5 annotations on purpose for the FlacocoMainTest?

Ups, my mistake. Thanks for pointing that. I fix it.

**Comment by martinezmatias** [comment]
Do you prefer to merge #35 first? 
If we merge now this PR, we can add the new  options later.

**Comment by andre15silva** [comment]
> Do you prefer to merge #35 first?
> If we merge now this PR, we can add the new options later.

We can merge this now, I think that's good.

I'll rebase the other one and implement the new options there.

**Pull request merged**
