### PR TITLE
Improve CI

### LINKED ISSUE #11: Class files of exampleFL3 not stored in the repo
Is there any reason why this is the case?

In `exampleFL1` and `exampleFL2`, the class files are in the git repo, but for `exampleFL3` they are computed during CI.

### LINKED ISSUE #14: Enable CI
- [x] Re-enable CI for test execution (#16)
- [x] Enable code coverage (#16)
- [x] Enable deployment in CI (#27)
- [x] Several JVM versions in CI (#27) Closes #5
- [x] Move to GitHub Actions (#27) Closes #5

### PR DESCRIPTION
**Pull request by andre15silva**
- [x] Remove target files from repo. (Closes #11 )
- [x] Introduce code coverage.
- [x] Improve CI config.

### CODE REVIEW

**Comment by andre15silva** [comment]
@martinezmatias I think re-generating the class files solved the NPE problem. The test that captures that behaviour is working now.

**Comment by andre15silva** [comment]
We need to request a new project in Sonatype's JIRA first, before setting up the deployment in CI.

I suggest we merge this and then have another PR for deployment only.

**Comment by martinezmatias** [comment]
Ready to merge, right?

**Comment by andre15silva** [comment]
> Ready to merge, right?

Rebasing, one sec.

**Comment by andre15silva** [comment]
Ready to merge @martinezmatias

**Comment by martinezmatias** [comment]
Great, thanks!

**Pull request merged**
