### PR TITLE
Exporter options for flacoco-cli

### PR DESCRIPTION
**Pull request by andre15silva**
Introduces exporting options in flacoco cli (CSV and JSON).

Related to #44.

This should be merged after #45, and #46, and rebasing.

### CODE REVIEW

**Comment by andre15silva** [comment]
Ready on green.

**Comment by andre15silva** [comment]
I've also added a small example to https://github.com/SpoonLabs/flacoco/wiki/CLI

**Comment by martinezmatias** [comment]
Hi @andre15silva 

> I've also added a small example to https://github.com/SpoonLabs/flacoco/wiki/CLI

that's perfect. Thanks. I just did a small change.

**Comment by andre15silva** [comment]
> I just did a small change.

Thanks!

**Comment by martinezmatias** [comment]
A minor proposition: (not sure if it makes sense)
Currently, when the user needs to export the results, she needs to pass two parameters a) format and b) output.
I would propose that, by default, we only need to specify one: the format.
For that, I would introduce two changes: first, that the interface FlacocoExporter has a method that returns the extension. Then, if no output is passed, we can export the results to a file without need the user adds a file (e.g., named results_flacoco_<timestamp> + appended the extension obtained from the exported).
Does this make sense?
Thanks
Matias

**Comment by andre15silva** [comment]
> A minor proposition: (not sure if it makes sense)
> Currently, when the user needs to export the results, she needs to pass two parameters a) format and b) output.
> I would propose that, by default, we only need to specify one: the format.

Currently the user only needs to specify one. The default output is the `stdout`.

> For that, I would introduce two changes: first, that the interface FlacocoExporter has a method that returns the extension. Then, if no output is passed, we can export the results to a file without need the user adds a file (e.g., named results_flacoco_ + appended the extension obtained from the exported).
> Does this make sense?

Do you think that is better than having the default being the `stdout`? It's a really simple change, but then we would lose the ability of outputting to `stdout`, which is useful sometimes I'd say.

What we could have, instead of asking the user to always specify a file path, is yet another flag which would output to a file with a default name. Then we would have three ways of specifying the output:
- No option selected -> `stdout`
- Output to file but no path provided -> default file
- Output to file and path provided -> provided file


WDYT?

**Comment by martinezmatias** [comment]
> Do you think that is better than having the default being the stdout?

I completely agree with that: no option -> stout

My point is that, if the user want to export the results to CSV, we can export the results without the need to asking him the file name. That output would be optional.

> No option selected -> stdout

Agree.

> Output to file but no path provided -> default file

My point is related to this point: we can ask the Exporter the extension of the file as we know the format of the content.

> Output to file and path provided -> provided file

Agree

**Comment by andre15silva** [comment]
Oh yes, my bad.

I was mixing the default value of `output` with `output` not even being specified.

I agree with the change. I'll add it in a moment.

**Comment by andre15silva** [comment]
Done @martinezmatias

**Comment by martinezmatias** [comment]
Perfect! Merged!

**Pull request merged**
