### PR TITLE
Optimize usage of test-runner

### PR DESCRIPTION
**Pull request by andre15silva**
Introduces the usage of test-runner with fully qualified method names, allowing for optimal usage, i.e. calling test-runner once per test framework.

To be merged after https://github.com/STAMP-project/test-runner/pull/99, https://github.com/STAMP-project/test-runner/pull/100, and https://github.com/SpoonLabs/flacoco/pull/45, as well as the rebase.

### CODE REVIEW

**Comment by andre15silva** [comment]
I separated this from #45 so it didn't get any bigger, and so that the commit in master doesn't contain two different issues.

**Comment by martinezmatias** [comment]
Hi @andre15silva 

> I separated this from #45 so it didn't get any bigger, and so that the commit in master doesn't contain two different issues.
Perfect. Do you agree to change the name of the PR to  something like: "Changes on the usage of test-runner"? 

Thanks.

**Comment by andre15silva** [comment]
> Hi @andre15silva

Hi @martinezmatias 

> Perfect. Do you agree to change the name of the PR to  something like: "Changes on the usage of test-runner"?

Yes, changed! My bad, that was the default title.

**Comment by martinezmatias** [comment]
Thanks :)

**Comment by andre15silva** [comment]
Ready after #45 is merged, and this is rebased.

**Comment by andre15silva** [comment]
Nooo, we should merge #45 first :grimacing:

**Comment by martinezmatias** [comment]
> Nooo, we should merge #45 first 😬

Ups, sorry :/

**Pull request merged**
