### PR TITLE
Flacoco spoon API

### PR DESCRIPTION
**Pull request by andre15silva**
The only issue right now is that different default keys can, in some cases, be mapped to the same `CtStatement`.

This means we should have a merge strategy for merging suspiciousness scores. Max, min, mean, median?

### CODE REVIEW

**Comment by martinezmatias** [comment]
> The only issue right now is that different default keys can, in some cases, be mapped to the same CtStatement. 
This means we should have a merge strategy for merging suspiciousness scores. Max, min, mean, median?

What do you mean with `default keys`? Do you mean the raw output of FL (i.e., list of tuple <File, Line number>)?

> This means we should have a merge strategy for merging suspiciousness scores. Max, min, mean, median?

Can be in practice possible to have lines with different suspicious values mapped to the same CtStatement? 
(I would think that no, but I am not sure)

**Comment by andre15silva** [comment]
> What do you mean with `default keys`? Do you mean the raw output of FL (i.e., list of tuple <File, Line number>)?

Yes, the raw output.

> Can be in practice possible to have lines with different suspicious values mapped to the same CtStatement?
> (I would think that no, but I am not sure)

I also think not, but I'm not sure either. Also, it depends on the formula. If there is a formula that takes into account the line position (is there?) then in that case it would definitely happen.

**Comment by martinezmatias** [comment]
> Also, it depends on the formula. If there is a formula that takes into account the line position or relative line position (is there?) then in that case it would definitely happen.

Actually a typical FL formula (e.g, tarantula, ochiai) computes the suspicious  *per Line*  based on numbers of passing/failing test cases that execute the line.

For example, if you have :
```
57    return a + 
58               b;
```
then,  the output of FL would be:
Line 57 suspicious 0.6
Line 58 suspicious 0.6

(I invented the suspicious value)

Consequently, I would be quite surprised if the raw FL output would assign two different suspicious values to elements within a parent CtStatement.

**Comment by andre15silva** [comment]
Alright, then I think there is no case where that happens. I added an error message just in case.

**Comment by andre15silva** [comment]
Ready for review @martinezmatias

**Comment by martinezmatias** [comment]
Perfect. I also think that that may vary according to the coverage tool used.  But it's nice to discuss these corner cases.

**Pull request merged**
