### PR TITLE
Move CI to Actions. Implement CD.

### LINKED ISSUE #14: Enable CI
- [x] Re-enable CI for test execution (#16)
- [x] Enable code coverage (#16)
- [x] Enable deployment in CI (#27)
- [x] Several JVM versions in CI (#27) Closes #5
- [x] Move to GitHub Actions (#27) Closes #5

### PR DESCRIPTION
**Pull request by andre15silva**
## Changelog

- Moved CI to Github Actions.
- Implemented CD of snapshots to Maven Central.

Closes #14

### CODE REVIEW

**Comment by andre15silva** [comment]
Ready for review

**Comment by martinezmatias** [comment]
It seems fine for me. However, I cannot merge it as the PR is still in Draft.

**Comment by andre15silva** [comment]
> It seems fine for me. However, I cannot merge it as the PR is still in Draft.

There was an unexpected build failure in CI. I'm taking a look at it now.

**Comment by andre15silva** [comment]
Ready now @martinezmatias .

Had to ignore `SpoonConverterTest` because it behaves differently in this CI (in Travis and locally it works). (See #28)

**Comment by martinezmatias** [comment]
Thanks @andre15silva , merged :)

**Pull request merged**
